# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\system-password\Files_UI\nova_janela_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 540)
        MainWindow.setMinimumSize(QtCore.QSize(830, 540))
        MainWindow.setMaximumSize(QtCore.QSize(830, 540))
        MainWindow.setBaseSize(QtCore.QSize(830, 540))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(830, 540))
        self.centralwidget.setMaximumSize(QtCore.QSize(830, 540))
        self.centralwidget.setBaseSize(QtCore.QSize(830, 540))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topo = QtWidgets.QFrame(self.centralwidget)
        self.topo.setMinimumSize(QtCore.QSize(0, 50))
        self.topo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topo.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.topo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topo.setObjectName("topo")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.topo)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton = QtWidgets.QPushButton(self.topo)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 50))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border:0px solid;\n"
"    background-position:center;\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(67, 67, 203);\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(22, 22))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_19.addWidget(self.pushButton)
        self.saida = QtWidgets.QFrame(self.topo)
        self.saida.setStyleSheet("QFrame{\n"
"    border-radius:10px\n"
"}")
        self.saida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saida.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saida.setObjectName("saida")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.saida)
        self.verticalLayout_7.setContentsMargins(233, 5, 0, 5)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.input = QtWidgets.QFrame(self.saida)
        self.input.setMaximumSize(QtCore.QSize(300, 16777215))
        self.input.setStyleSheet("QFrame{\n"
"    background-color: rgb(63, 255, 53);\n"
"}\n"
"")
        self.input.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input.setObjectName("input")
        self.input_saida = QtWidgets.QLabel(self.input)
        self.input_saida.setGeometry(QtCore.QRect(9, 9, 254, 22))
        self.input_saida.setMaximumSize(QtCore.QSize(300, 32))
        self.input_saida.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.input_saida.setText("")
        self.input_saida.setAlignment(QtCore.Qt.AlignCenter)
        self.input_saida.setObjectName("input_saida")
        self.botao_saida = QtWidgets.QPushButton(self.input)
        self.botao_saida.setGeometry(QtCore.QRect(266, 7, 25, 25))
        self.botao_saida.setMinimumSize(QtCore.QSize(25, 25))
        self.botao_saida.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.botao_saida.setFont(font)
        self.botao_saida.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_saida.setStyleSheet("QPushButton{\n"
"    border-radius:3px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(21, 21, 21)\n"
"}")
        self.botao_saida.setText("")
        self.botao_saida.setIconSize(QtCore.QSize(14, 14))
        self.botao_saida.setObjectName("botao_saida")
        self.verticalLayout_7.addWidget(self.input)
        self.horizontalLayout_19.addWidget(self.saida)
        self.verticalLayout.addWidget(self.topo)
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_conteudo = QtWidgets.QFrame(self.main)
        self.menu_conteudo.setMinimumSize(QtCore.QSize(50, 465))
        self.menu_conteudo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.menu_conteudo.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.menu_conteudo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_conteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_conteudo.setObjectName("menu_conteudo")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.menu_conteudo)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_cadastrar = QtWidgets.QFrame(self.menu_conteudo)
        self.frame_cadastrar.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_cadastrar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_cadastrar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_cadastrar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cadastrar.setObjectName("frame_cadastrar")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_cadastrar)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.botao_aba_cadastrar = QtWidgets.QPushButton(self.frame_cadastrar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_aba_cadastrar.sizePolicy().hasHeightForWidth())
        self.botao_aba_cadastrar.setSizePolicy(sizePolicy)
        self.botao_aba_cadastrar.setMinimumSize(QtCore.QSize(50, 50))
        self.botao_aba_cadastrar.setMaximumSize(QtCore.QSize(50, 50))
        self.botao_aba_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_aba_cadastrar.setToolTipDuration(-1)
        self.botao_aba_cadastrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_aba_cadastrar.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border:0px solid;\n"
"    background-color: rgb(30, 30, 30);\n"
"    background-position:center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(67, 67, 203);\n"
"}\n"
"")
        self.botao_aba_cadastrar.setText("")
        self.botao_aba_cadastrar.setIconSize(QtCore.QSize(30, 30))
        self.botao_aba_cadastrar.setObjectName("botao_aba_cadastrar")
        self.horizontalLayout_27.addWidget(self.botao_aba_cadastrar)
        self.label_5 = QtWidgets.QLabel(self.frame_cadastrar)
        self.label_5.setMinimumSize(QtCore.QSize(90, 50))
        self.label_5.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setPointSize(9)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    text-shadow: 1px 1px rgb(85, 85, 255);\n"
"    color:rgb(211, 211, 211)\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_27.addWidget(self.label_5)
        self.label_5.raise_()
        self.botao_aba_cadastrar.raise_()
        self.verticalLayout_8.addWidget(self.frame_cadastrar)
        self.frame_login = QtWidgets.QFrame(self.menu_conteudo)
        self.frame_login.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_login.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_login.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_login)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.botao_aba_login = QtWidgets.QPushButton(self.frame_login)
        self.botao_aba_login.setMinimumSize(QtCore.QSize(50, 50))
        self.botao_aba_login.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.botao_aba_login.setFont(font)
        self.botao_aba_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_aba_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_aba_login.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border:0px solid;\n"
"    background-color: rgb(30, 30, 30);\n"
"    background-position:center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(67, 67, 203);\n"
"}\n"
"")
        self.botao_aba_login.setText("")
        self.botao_aba_login.setIconSize(QtCore.QSize(30, 32))
        self.botao_aba_login.setObjectName("botao_aba_login")
        self.horizontalLayout_29.addWidget(self.botao_aba_login)
        self.label_15 = QtWidgets.QLabel(self.frame_login)
        self.label_15.setMinimumSize(QtCore.QSize(90, 50))
        self.label_15.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel{\n"
"    text-shadow: 1px 1px rgb(85, 85, 255);\n"
"    color:rgb(211, 211, 211)\n"
"}")
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_29.addWidget(self.label_15)
        self.label_15.raise_()
        self.botao_aba_login.raise_()
        self.verticalLayout_8.addWidget(self.frame_login)
        self.frame_senha = QtWidgets.QFrame(self.menu_conteudo)
        self.frame_senha.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_senha.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_senha.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_senha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_senha.setObjectName("frame_senha")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_senha)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.botao_aba_senha = QtWidgets.QPushButton(self.frame_senha)
        self.botao_aba_senha.setMinimumSize(QtCore.QSize(50, 50))
        self.botao_aba_senha.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.botao_aba_senha.setFont(font)
        self.botao_aba_senha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_aba_senha.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_aba_senha.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border:0px solid;\n"
"    background-color: rgb(30, 30, 30);\n"
"    background-position:center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(67, 67, 203);\n"
"}\n"
"")
        self.botao_aba_senha.setText("")
        self.botao_aba_senha.setIconSize(QtCore.QSize(30, 32))
        self.botao_aba_senha.setObjectName("botao_aba_senha")
        self.horizontalLayout_26.addWidget(self.botao_aba_senha)
        self.label_6 = QtWidgets.QLabel(self.frame_senha)
        self.label_6.setMinimumSize(QtCore.QSize(90, 50))
        self.label_6.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setPointSize(7)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    text-shadow: 1px 1px rgb(85, 85, 255);\n"
"    color:rgb(211, 211, 211)\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_26.addWidget(self.label_6)
        self.label_6.raise_()
        self.botao_aba_senha.raise_()
        self.verticalLayout_8.addWidget(self.frame_senha)
        self.frame_info = QtWidgets.QFrame(self.menu_conteudo)
        self.frame_info.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_info.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_info)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.botao_aba_info = QtWidgets.QPushButton(self.frame_info)
        self.botao_aba_info.setMinimumSize(QtCore.QSize(50, 50))
        self.botao_aba_info.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_aba_info.setFont(font)
        self.botao_aba_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_aba_info.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_aba_info.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border:0px solid;\n"
"    background-color: rgb(30, 30, 30);\n"
"    background-position:center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(67, 67, 203);\n"
"}\n"
"")
        self.botao_aba_info.setText("")
        self.botao_aba_info.setIconSize(QtCore.QSize(32, 32))
        self.botao_aba_info.setObjectName("botao_aba_info")
        self.horizontalLayout_28.addWidget(self.botao_aba_info)
        self.label_12 = QtWidgets.QLabel(self.frame_info)
        self.label_12.setMinimumSize(QtCore.QSize(90, 50))
        self.label_12.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    text-shadow: 1px 1px rgb(85, 85, 255);\n"
"    color:rgb(211, 211, 211)\n"
"}")
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_28.addWidget(self.label_12)
        self.label_12.raise_()
        self.botao_aba_info.raise_()
        self.verticalLayout_8.addWidget(self.frame_info)
        self.frame_9 = QtWidgets.QFrame(self.menu_conteudo)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8.addWidget(self.frame_9)
        self.frame_senha.raise_()
        self.frame_cadastrar.raise_()
        self.frame_info.raise_()
        self.frame_9.raise_()
        self.frame_login.raise_()
        self.horizontalLayout.addWidget(self.menu_conteudo, 0, QtCore.Qt.AlignTop)
        self.conteudoo = QtWidgets.QFrame(self.main)
        self.conteudoo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conteudoo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteudoo.setObjectName("conteudoo")
        self.login = QtWidgets.QFrame(self.conteudoo)
        self.login.setGeometry(QtCore.QRect(0, 0, 771, 465))
        self.login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login.setObjectName("login")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.login)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.login)
        self.frame.setMinimumSize(QtCore.QSize(100, 100))
        self.frame.setMaximumSize(QtCore.QSize(10000000, 16777214))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(270, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(160, 50))
        self.label_3.setMaximumSize(QtCore.QSize(1111, 11111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_22.addWidget(self.label_3)
        self.img_contas = QtWidgets.QLabel(self.frame_3)
        self.img_contas.setMinimumSize(QtCore.QSize(64, 0))
        self.img_contas.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.img_contas.setFont(font)
        self.img_contas.setStyleSheet("background-position:center;\n"
"background-size: 64px 64px;")
        self.img_contas.setText("")
        self.img_contas.setObjectName("img_contas")
        self.horizontalLayout_22.addWidget(self.img_contas)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.login)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(90, 0, 90, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(131, 255, 131);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_20.addWidget(self.label_4)
        self.label_9 = QtWidgets.QLabel(self.frame_8)
        self.label_9.setMinimumSize(QtCore.QSize(370, 0))
        self.label_9.setMaximumSize(QtCore.QSize(370, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(98, 98, 98);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_20.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 115, 117);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollArea_2.setStyleSheet("QScrollBar:vertical{\n"
"    boder:none;\n"
"    background-color:rgb(0, 0, 0);\n"
"    width:14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius:0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical{\n"
"    background-color:rgb(0, 0, 0);\n"
"    border-radius:3px;\n"
"    min-height:30px\n"
"}\n"
"\n"
"QScrollBar::handle:hover{\n"
"    background-color:#42414d;\n"
"}\n"
"\n"
"QScrollBar::handle:pressed{\n"
"    background-color:rgb(55, 55, 55);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    boder:none;\n"
"    background-color:rgb(0, 0, 0);\n"
"    height:15px;\n"
"    border-top-left-radius:3px    ;\n"
"    border-top-right-radius:    3px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"    \n"
"}\n"
"\n"
"QScrollBar::sub-line:hover{\n"
"    background-color:#42414d;\n"
"}\n"
"\n"
"QScrollBar::sub-line:pressed{\n"
"    background-color:rgb(55, 55, 55);\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    boder:none;\n"
"    background-color:rgb(0, 0, 0);\n"
"    height:15px;\n"
"    border-bottom-left-radius:3px    ;\n"
"    border-bottom-right-radius:3px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"    \n"
"}\n"
"\n"
"QScrollBar::add-line:hover{\n"
"    background-color:#42414d;\n"
"}\n"
"\n"
"QScrollBar::add-line:pressed{\n"
"    background-color:rgb(55, 55, 55);\n"
"}\n"
"\n"
"*{\n"
"background-color:rgb(116, 116, 116);\n"
"}")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 568, 1500))
        self.scrollAreaWidgetContents_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.list_users = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.list_users.setMinimumSize(QtCore.QSize(0, 1500))
        self.list_users.setStyleSheet("")
        self.list_users.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_users.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_users.setObjectName("list_users")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.list_users)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.user_1 = QtWidgets.QFrame(self.list_users)
        self.user_1.setMinimumSize(QtCore.QSize(343, 91))
        self.user_1.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_1.setObjectName("user_1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.user_1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.botao_entrar_1 = QtWidgets.QPushButton(self.user_1)
        self.botao_entrar_1.setEnabled(False)
        self.botao_entrar_1.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_1.setStyleSheet("QPushButton{\n"
"    border-radius: 50px;\n"
"}")
        self.botao_entrar_1.setText("")
        self.botao_entrar_1.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_1.setObjectName("botao_entrar_1")
        self.horizontalLayout_4.addWidget(self.botao_entrar_1)
        self.nome_da_conta_1 = QtWidgets.QLabel(self.user_1)
        self.nome_da_conta_1.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_1.setFont(font)
        self.nome_da_conta_1.setText("")
        self.nome_da_conta_1.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_1.setObjectName("nome_da_conta_1")
        self.horizontalLayout_4.addWidget(self.nome_da_conta_1)
        self.botao_apagar_1 = QtWidgets.QPushButton(self.user_1)
        self.botao_apagar_1.setEnabled(False)
        self.botao_apagar_1.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(10)
        self.botao_apagar_1.setFont(font)
        self.botao_apagar_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_1.setAcceptDrops(False)
        self.botao_apagar_1.setStyleSheet("border-radius:1px;")
        self.botao_apagar_1.setText("")
        self.botao_apagar_1.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_1.setObjectName("botao_apagar_1")
        self.horizontalLayout_4.addWidget(self.botao_apagar_1)
        self.verticalLayout_3.addWidget(self.user_1)
        self.user_2 = QtWidgets.QFrame(self.list_users)
        self.user_2.setMinimumSize(QtCore.QSize(343, 91))
        self.user_2.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_2.setObjectName("user_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.user_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.botao_entrar_2 = QtWidgets.QPushButton(self.user_2)
        self.botao_entrar_2.setEnabled(False)
        self.botao_entrar_2.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_2.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_2.setText("")
        self.botao_entrar_2.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_2.setObjectName("botao_entrar_2")
        self.horizontalLayout_5.addWidget(self.botao_entrar_2)
        self.nome_da_conta_2 = QtWidgets.QLabel(self.user_2)
        self.nome_da_conta_2.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_2.setFont(font)
        self.nome_da_conta_2.setText("")
        self.nome_da_conta_2.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_2.setObjectName("nome_da_conta_2")
        self.horizontalLayout_5.addWidget(self.nome_da_conta_2)
        self.botao_apagar_2 = QtWidgets.QPushButton(self.user_2)
        self.botao_apagar_2.setEnabled(False)
        self.botao_apagar_2.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_2.setAcceptDrops(False)
        self.botao_apagar_2.setStyleSheet("border-radius:1px;")
        self.botao_apagar_2.setText("")
        self.botao_apagar_2.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_2.setObjectName("botao_apagar_2")
        self.horizontalLayout_5.addWidget(self.botao_apagar_2)
        self.verticalLayout_3.addWidget(self.user_2)
        self.user_3 = QtWidgets.QFrame(self.list_users)
        self.user_3.setMinimumSize(QtCore.QSize(343, 91))
        self.user_3.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_3.setObjectName("user_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.user_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.botao_entrar_3 = QtWidgets.QPushButton(self.user_3)
        self.botao_entrar_3.setEnabled(False)
        self.botao_entrar_3.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_3.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_3.setText("")
        self.botao_entrar_3.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_3.setObjectName("botao_entrar_3")
        self.horizontalLayout_6.addWidget(self.botao_entrar_3)
        self.nome_da_conta_3 = QtWidgets.QLabel(self.user_3)
        self.nome_da_conta_3.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_3.setFont(font)
        self.nome_da_conta_3.setText("")
        self.nome_da_conta_3.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_3.setObjectName("nome_da_conta_3")
        self.horizontalLayout_6.addWidget(self.nome_da_conta_3)
        self.botao_apagar_3 = QtWidgets.QPushButton(self.user_3)
        self.botao_apagar_3.setEnabled(False)
        self.botao_apagar_3.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_3.setAcceptDrops(False)
        self.botao_apagar_3.setStyleSheet("border-radius:1px;")
        self.botao_apagar_3.setText("")
        self.botao_apagar_3.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_3.setObjectName("botao_apagar_3")
        self.horizontalLayout_6.addWidget(self.botao_apagar_3)
        self.verticalLayout_3.addWidget(self.user_3)
        self.user_4 = QtWidgets.QFrame(self.list_users)
        self.user_4.setMinimumSize(QtCore.QSize(343, 91))
        self.user_4.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_4.setObjectName("user_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.user_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.botao_entrar_4 = QtWidgets.QPushButton(self.user_4)
        self.botao_entrar_4.setEnabled(False)
        self.botao_entrar_4.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_4.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_4.setText("")
        self.botao_entrar_4.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_4.setObjectName("botao_entrar_4")
        self.horizontalLayout_7.addWidget(self.botao_entrar_4)
        self.nome_da_conta_4 = QtWidgets.QLabel(self.user_4)
        self.nome_da_conta_4.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_4.setFont(font)
        self.nome_da_conta_4.setText("")
        self.nome_da_conta_4.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_4.setObjectName("nome_da_conta_4")
        self.horizontalLayout_7.addWidget(self.nome_da_conta_4)
        self.botao_apagar_4 = QtWidgets.QPushButton(self.user_4)
        self.botao_apagar_4.setEnabled(False)
        self.botao_apagar_4.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_4.setAcceptDrops(False)
        self.botao_apagar_4.setStyleSheet("border-radius:1px;")
        self.botao_apagar_4.setText("")
        self.botao_apagar_4.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_4.setObjectName("botao_apagar_4")
        self.horizontalLayout_7.addWidget(self.botao_apagar_4)
        self.verticalLayout_3.addWidget(self.user_4)
        self.user_5 = QtWidgets.QFrame(self.list_users)
        self.user_5.setMinimumSize(QtCore.QSize(343, 91))
        self.user_5.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_5.setObjectName("user_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.user_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.botao_entrar_5 = QtWidgets.QPushButton(self.user_5)
        self.botao_entrar_5.setEnabled(False)
        self.botao_entrar_5.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_5.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_5.setText("")
        self.botao_entrar_5.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_5.setObjectName("botao_entrar_5")
        self.horizontalLayout_8.addWidget(self.botao_entrar_5)
        self.nome_da_conta_5 = QtWidgets.QLabel(self.user_5)
        self.nome_da_conta_5.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_5.setFont(font)
        self.nome_da_conta_5.setText("")
        self.nome_da_conta_5.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_5.setObjectName("nome_da_conta_5")
        self.horizontalLayout_8.addWidget(self.nome_da_conta_5)
        self.botao_apagar_5 = QtWidgets.QPushButton(self.user_5)
        self.botao_apagar_5.setEnabled(False)
        self.botao_apagar_5.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_5.setAcceptDrops(False)
        self.botao_apagar_5.setStyleSheet("border-radius:1px;")
        self.botao_apagar_5.setText("")
        self.botao_apagar_5.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_5.setObjectName("botao_apagar_5")
        self.horizontalLayout_8.addWidget(self.botao_apagar_5)
        self.verticalLayout_3.addWidget(self.user_5)
        self.user_6 = QtWidgets.QFrame(self.list_users)
        self.user_6.setMinimumSize(QtCore.QSize(343, 91))
        self.user_6.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_6.setObjectName("user_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.user_6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.botao_entrar_6 = QtWidgets.QPushButton(self.user_6)
        self.botao_entrar_6.setEnabled(False)
        self.botao_entrar_6.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_6.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_6.setText("")
        self.botao_entrar_6.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_6.setObjectName("botao_entrar_6")
        self.horizontalLayout_9.addWidget(self.botao_entrar_6)
        self.nome_da_conta_6 = QtWidgets.QLabel(self.user_6)
        self.nome_da_conta_6.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_6.setFont(font)
        self.nome_da_conta_6.setText("")
        self.nome_da_conta_6.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_6.setObjectName("nome_da_conta_6")
        self.horizontalLayout_9.addWidget(self.nome_da_conta_6)
        self.botao_apagar_6 = QtWidgets.QPushButton(self.user_6)
        self.botao_apagar_6.setEnabled(False)
        self.botao_apagar_6.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_6.setAcceptDrops(False)
        self.botao_apagar_6.setStyleSheet("border-radius:1px;")
        self.botao_apagar_6.setText("")
        self.botao_apagar_6.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_6.setObjectName("botao_apagar_6")
        self.horizontalLayout_9.addWidget(self.botao_apagar_6)
        self.verticalLayout_3.addWidget(self.user_6)
        self.user_7 = QtWidgets.QFrame(self.list_users)
        self.user_7.setMinimumSize(QtCore.QSize(343, 91))
        self.user_7.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_7.setObjectName("user_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.user_7)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.botao_entrar_7 = QtWidgets.QPushButton(self.user_7)
        self.botao_entrar_7.setEnabled(False)
        self.botao_entrar_7.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_7.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_7.setText("")
        self.botao_entrar_7.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_7.setObjectName("botao_entrar_7")
        self.horizontalLayout_10.addWidget(self.botao_entrar_7)
        self.nome_da_conta_7 = QtWidgets.QLabel(self.user_7)
        self.nome_da_conta_7.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_7.setFont(font)
        self.nome_da_conta_7.setText("")
        self.nome_da_conta_7.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_7.setObjectName("nome_da_conta_7")
        self.horizontalLayout_10.addWidget(self.nome_da_conta_7)
        self.botao_apagar_7 = QtWidgets.QPushButton(self.user_7)
        self.botao_apagar_7.setEnabled(False)
        self.botao_apagar_7.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_7.setAcceptDrops(False)
        self.botao_apagar_7.setStyleSheet("border-radius:1px;")
        self.botao_apagar_7.setText("")
        self.botao_apagar_7.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_7.setObjectName("botao_apagar_7")
        self.horizontalLayout_10.addWidget(self.botao_apagar_7)
        self.verticalLayout_3.addWidget(self.user_7)
        self.user_8 = QtWidgets.QFrame(self.list_users)
        self.user_8.setMinimumSize(QtCore.QSize(343, 91))
        self.user_8.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_8.setObjectName("user_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.user_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.botao_entrar_8 = QtWidgets.QPushButton(self.user_8)
        self.botao_entrar_8.setEnabled(False)
        self.botao_entrar_8.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_8.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_8.setText("")
        self.botao_entrar_8.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_8.setObjectName("botao_entrar_8")
        self.horizontalLayout_11.addWidget(self.botao_entrar_8)
        self.nome_da_conta_8 = QtWidgets.QLabel(self.user_8)
        self.nome_da_conta_8.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_8.setFont(font)
        self.nome_da_conta_8.setText("")
        self.nome_da_conta_8.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_8.setObjectName("nome_da_conta_8")
        self.horizontalLayout_11.addWidget(self.nome_da_conta_8)
        self.botao_apagar_8 = QtWidgets.QPushButton(self.user_8)
        self.botao_apagar_8.setEnabled(False)
        self.botao_apagar_8.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_8.setAcceptDrops(False)
        self.botao_apagar_8.setStyleSheet("border-radius:1px;")
        self.botao_apagar_8.setText("")
        self.botao_apagar_8.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_8.setObjectName("botao_apagar_8")
        self.horizontalLayout_11.addWidget(self.botao_apagar_8)
        self.verticalLayout_3.addWidget(self.user_8)
        self.user_9 = QtWidgets.QFrame(self.list_users)
        self.user_9.setMinimumSize(QtCore.QSize(343, 91))
        self.user_9.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_9.setObjectName("user_9")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.user_9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.botao_entrar_9 = QtWidgets.QPushButton(self.user_9)
        self.botao_entrar_9.setEnabled(False)
        self.botao_entrar_9.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_9.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_9.setText("")
        self.botao_entrar_9.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_9.setObjectName("botao_entrar_9")
        self.horizontalLayout_12.addWidget(self.botao_entrar_9)
        self.nome_da_conta_9 = QtWidgets.QLabel(self.user_9)
        self.nome_da_conta_9.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_9.setFont(font)
        self.nome_da_conta_9.setText("")
        self.nome_da_conta_9.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_9.setObjectName("nome_da_conta_9")
        self.horizontalLayout_12.addWidget(self.nome_da_conta_9)
        self.botao_apagar_9 = QtWidgets.QPushButton(self.user_9)
        self.botao_apagar_9.setEnabled(False)
        self.botao_apagar_9.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_9.setAcceptDrops(False)
        self.botao_apagar_9.setStyleSheet("border-radius:1px;")
        self.botao_apagar_9.setText("")
        self.botao_apagar_9.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_9.setObjectName("botao_apagar_9")
        self.horizontalLayout_12.addWidget(self.botao_apagar_9)
        self.verticalLayout_3.addWidget(self.user_9)
        self.user_10 = QtWidgets.QFrame(self.list_users)
        self.user_10.setMinimumSize(QtCore.QSize(343, 91))
        self.user_10.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_10.setObjectName("user_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.user_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.botao_entrar_10 = QtWidgets.QPushButton(self.user_10)
        self.botao_entrar_10.setEnabled(False)
        self.botao_entrar_10.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_10.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_10.setText("")
        self.botao_entrar_10.setIconSize(QtCore.QSize(100, 96))
        self.botao_entrar_10.setObjectName("botao_entrar_10")
        self.horizontalLayout_13.addWidget(self.botao_entrar_10)
        self.nome_da_conta_10 = QtWidgets.QLabel(self.user_10)
        self.nome_da_conta_10.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_10.setFont(font)
        self.nome_da_conta_10.setText("")
        self.nome_da_conta_10.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_10.setObjectName("nome_da_conta_10")
        self.horizontalLayout_13.addWidget(self.nome_da_conta_10)
        self.botao_apagar_10 = QtWidgets.QPushButton(self.user_10)
        self.botao_apagar_10.setEnabled(False)
        self.botao_apagar_10.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_10.setAcceptDrops(False)
        self.botao_apagar_10.setStyleSheet("border-radius:1px;")
        self.botao_apagar_10.setText("")
        self.botao_apagar_10.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_10.setObjectName("botao_apagar_10")
        self.horizontalLayout_13.addWidget(self.botao_apagar_10)
        self.verticalLayout_3.addWidget(self.user_10)
        self.user_11 = QtWidgets.QFrame(self.list_users)
        self.user_11.setMinimumSize(QtCore.QSize(343, 91))
        self.user_11.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_11.setObjectName("user_11")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.user_11)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.botao_entrar_11 = QtWidgets.QPushButton(self.user_11)
        self.botao_entrar_11.setEnabled(False)
        self.botao_entrar_11.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_11.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_11.setText("")
        self.botao_entrar_11.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_11.setObjectName("botao_entrar_11")
        self.horizontalLayout_14.addWidget(self.botao_entrar_11)
        self.nome_da_conta_11 = QtWidgets.QLabel(self.user_11)
        self.nome_da_conta_11.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_11.setFont(font)
        self.nome_da_conta_11.setText("")
        self.nome_da_conta_11.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_11.setObjectName("nome_da_conta_11")
        self.horizontalLayout_14.addWidget(self.nome_da_conta_11)
        self.botao_apagar_11 = QtWidgets.QPushButton(self.user_11)
        self.botao_apagar_11.setEnabled(False)
        self.botao_apagar_11.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_11.setAcceptDrops(False)
        self.botao_apagar_11.setStyleSheet("border-radius:1px;")
        self.botao_apagar_11.setText("")
        self.botao_apagar_11.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_11.setObjectName("botao_apagar_11")
        self.horizontalLayout_14.addWidget(self.botao_apagar_11)
        self.verticalLayout_3.addWidget(self.user_11)
        self.user_12 = QtWidgets.QFrame(self.list_users)
        self.user_12.setMinimumSize(QtCore.QSize(343, 91))
        self.user_12.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_12.setObjectName("user_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.user_12)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.botao_entrar_12 = QtWidgets.QPushButton(self.user_12)
        self.botao_entrar_12.setEnabled(False)
        self.botao_entrar_12.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_12.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_12.setText("")
        self.botao_entrar_12.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_12.setObjectName("botao_entrar_12")
        self.horizontalLayout_15.addWidget(self.botao_entrar_12)
        self.nome_da_conta_12 = QtWidgets.QLabel(self.user_12)
        self.nome_da_conta_12.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_12.setFont(font)
        self.nome_da_conta_12.setText("")
        self.nome_da_conta_12.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_12.setObjectName("nome_da_conta_12")
        self.horizontalLayout_15.addWidget(self.nome_da_conta_12)
        self.botao_apagar_12 = QtWidgets.QPushButton(self.user_12)
        self.botao_apagar_12.setEnabled(False)
        self.botao_apagar_12.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_12.setAcceptDrops(False)
        self.botao_apagar_12.setStyleSheet("border-radius:1px;")
        self.botao_apagar_12.setText("")
        self.botao_apagar_12.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_12.setObjectName("botao_apagar_12")
        self.horizontalLayout_15.addWidget(self.botao_apagar_12)
        self.verticalLayout_3.addWidget(self.user_12)
        self.user_13 = QtWidgets.QFrame(self.list_users)
        self.user_13.setMinimumSize(QtCore.QSize(343, 91))
        self.user_13.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_13.setObjectName("user_13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.user_13)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.botao_entrar_13 = QtWidgets.QPushButton(self.user_13)
        self.botao_entrar_13.setEnabled(False)
        self.botao_entrar_13.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_13.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_13.setText("")
        self.botao_entrar_13.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_13.setObjectName("botao_entrar_13")
        self.horizontalLayout_16.addWidget(self.botao_entrar_13)
        self.nome_da_conta_13 = QtWidgets.QLabel(self.user_13)
        self.nome_da_conta_13.setMaximumSize(QtCore.QSize(250, 70))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_13.setFont(font)
        self.nome_da_conta_13.setText("")
        self.nome_da_conta_13.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_13.setObjectName("nome_da_conta_13")
        self.horizontalLayout_16.addWidget(self.nome_da_conta_13)
        self.botao_apagar_13 = QtWidgets.QPushButton(self.user_13)
        self.botao_apagar_13.setEnabled(False)
        self.botao_apagar_13.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_13.setAcceptDrops(False)
        self.botao_apagar_13.setStyleSheet("border-radius:1px;")
        self.botao_apagar_13.setText("")
        self.botao_apagar_13.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_13.setObjectName("botao_apagar_13")
        self.horizontalLayout_16.addWidget(self.botao_apagar_13)
        self.verticalLayout_3.addWidget(self.user_13)
        self.user_14 = QtWidgets.QFrame(self.list_users)
        self.user_14.setMinimumSize(QtCore.QSize(343, 91))
        self.user_14.setMaximumSize(QtCore.QSize(1000, 120))
        self.user_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_14.setObjectName("user_14")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.user_14)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.botao_entrar_14 = QtWidgets.QPushButton(self.user_14)
        self.botao_entrar_14.setEnabled(False)
        self.botao_entrar_14.setMaximumSize(QtCore.QSize(100, 100))
        self.botao_entrar_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_entrar_14.setStyleSheet("border-radius:1px;\n"
"")
        self.botao_entrar_14.setText("")
        self.botao_entrar_14.setIconSize(QtCore.QSize(96, 96))
        self.botao_entrar_14.setObjectName("botao_entrar_14")
        self.horizontalLayout_17.addWidget(self.botao_entrar_14)
        self.nome_da_conta_14 = QtWidgets.QLabel(self.user_14)
        self.nome_da_conta_14.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nome_da_conta_14.setFont(font)
        self.nome_da_conta_14.setText("")
        self.nome_da_conta_14.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_da_conta_14.setObjectName("nome_da_conta_14")
        self.horizontalLayout_17.addWidget(self.nome_da_conta_14)
        self.botao_apagar_14 = QtWidgets.QPushButton(self.user_14)
        self.botao_apagar_14.setEnabled(False)
        self.botao_apagar_14.setMaximumSize(QtCore.QSize(64, 64))
        self.botao_apagar_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_apagar_14.setAcceptDrops(False)
        self.botao_apagar_14.setStyleSheet("border-radius:1px;")
        self.botao_apagar_14.setText("")
        self.botao_apagar_14.setIconSize(QtCore.QSize(64, 64))
        self.botao_apagar_14.setObjectName("botao_apagar_14")
        self.horizontalLayout_17.addWidget(self.botao_apagar_14)
        self.verticalLayout_3.addWidget(self.user_14)
        self.gridLayout_2.addWidget(self.list_users, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(93, 93, 93);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.cadastrar = QtWidgets.QFrame(self.conteudoo)
        self.cadastrar.setGeometry(QtCore.QRect(0, 0, 771, 465))
        self.cadastrar.setMinimumSize(QtCore.QSize(0, 465))
        self.cadastrar.setMaximumSize(QtCore.QSize(16777215, 465))
        self.cadastrar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cadastrar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cadastrar.setObjectName("cadastrar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cadastrar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.cadastrar)
        self.frame_4.setMaximumSize(QtCore.QSize(10000000, 90))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(270, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setMinimumSize(QtCore.QSize(160, 50))
        self.label_2.setMaximumSize(QtCore.QSize(1111, 1111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_24.addWidget(self.label_2)
        self.img_criar = QtWidgets.QLabel(self.frame_6)
        self.img_criar.setMinimumSize(QtCore.QSize(64, 64))
        self.img_criar.setMaximumSize(QtCore.QSize(64, 64))
        self.img_criar.setSizeIncrement(QtCore.QSize(64, 64))
        self.img_criar.setBaseSize(QtCore.QSize(64, 64))
        self.img_criar.setStyleSheet("background-position:center;\n"
"background-size: 64px 64px;")
        self.img_criar.setText("")
        self.img_criar.setObjectName("img_criar")
        self.horizontalLayout_24.addWidget(self.img_criar)
        self.horizontalLayout_23.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.cadastrar)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_7.setStyleSheet("QFrame{    \n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.input_nome_2 = QtWidgets.QLineEdit(self.frame_7)
        self.input_nome_2.setGeometry(QtCore.QRect(20, 190, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_nome_2.setFont(font)
        self.input_nome_2.setStyleSheet("QLineEdit{\n"
"    color: rgb(135, 135, 135);\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-radius:10px;\n"
"    border: 2px solid;\n"
"    padding: 10px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    color: rgb(135, 135, 135);\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.input_nome_2.setMaxLength(15)
        self.input_nome_2.setObjectName("input_nome_2")
        self.input_sobrenome_2 = QtWidgets.QLineEdit(self.frame_7)
        self.input_sobrenome_2.setGeometry(QtCore.QRect(20, 256, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_sobrenome_2.setFont(font)
        self.input_sobrenome_2.setStyleSheet("QLineEdit{\n"
"    color: rgb(135, 135, 135);\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-radius:10px;\n"
"    border: 2px solid;\n"
"    padding:10px\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    color: rgb(135, 135, 135);\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.input_sobrenome_2.setMaxLength(20)
        self.input_sobrenome_2.setObjectName("input_sobrenome_2")
        self.avatar_1 = QtWidgets.QPushButton(self.frame_7)
        self.avatar_1.setGeometry(QtCore.QRect(20, 150, 32, 32))
        self.avatar_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatar_1.setStyleSheet("QPushButton{\n"
"    border-radius:16px;\n"
"    border: 2px solid;\n"
"    background-position:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"}")
        self.avatar_1.setText("")
        self.avatar_1.setIconSize(QtCore.QSize(40, 40))
        self.avatar_1.setObjectName("avatar_1")
        self.avatar_4 = QtWidgets.QPushButton(self.frame_7)
        self.avatar_4.setGeometry(QtCore.QRect(152, 150, 32, 32))
        self.avatar_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatar_4.setStyleSheet("QPushButton{\n"
"    border-radius:16px;\n"
"    border: 2px solid;\n"
"    background-position:center;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"}")
        self.avatar_4.setText("")
        self.avatar_4.setIconSize(QtCore.QSize(32, 32))
        self.avatar_4.setObjectName("avatar_4")
        self.avatar_2 = QtWidgets.QPushButton(self.frame_7)
        self.avatar_2.setGeometry(QtCore.QRect(64, 150, 32, 32))
        self.avatar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatar_2.setStyleSheet("QPushButton{\n"
"    border-radius:16px;\n"
"    border: 2px solid;\n"
"    background-position:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"}")
        self.avatar_2.setText("")
        self.avatar_2.setIconSize(QtCore.QSize(32, 32))
        self.avatar_2.setObjectName("avatar_2")
        self.avatar_3 = QtWidgets.QPushButton(self.frame_7)
        self.avatar_3.setGeometry(QtCore.QRect(108, 150, 32, 32))
        self.avatar_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatar_3.setStyleSheet("QPushButton{\n"
"    border-radius:16px;\n"
"    border: 2px solid;\n"
"    background-position:center;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"}")
        self.avatar_3.setText("")
        self.avatar_3.setIconSize(QtCore.QSize(32, 32))
        self.avatar_3.setObjectName("avatar_3")
        self.avatar_5 = QtWidgets.QPushButton(self.frame_7)
        self.avatar_5.setGeometry(QtCore.QRect(196, 150, 32, 32))
        self.avatar_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatar_5.setStyleSheet("QPushButton{\n"
"    border-radius:16px;\n"
"    border: 2px solid;\n"
"    background-position:center;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"}")
        self.avatar_5.setText("")
        self.avatar_5.setIconSize(QtCore.QSize(32, 32))
        self.avatar_5.setObjectName("avatar_5")
        self.avatar_6 = QtWidgets.QPushButton(self.frame_7)
        self.avatar_6.setGeometry(QtCore.QRect(240, 150, 32, 32))
        self.avatar_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.avatar_6.setStyleSheet("QPushButton{\n"
"    border-radius:16px;\n"
"    border: 2px solid;\n"
"    background-position:center;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(85, 85, 255);\n"
"}")
        self.avatar_6.setText("")
        self.avatar_6.setIconSize(QtCore.QSize(32, 32))
        self.avatar_6.setObjectName("avatar_6")
        self.btn_criar_2 = QtWidgets.QPushButton(self.frame_7)
        self.btn_criar_2.setGeometry(QtCore.QRect(50, 330, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_criar_2.setFont(font)
        self.btn_criar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_criar_2.setStyleSheet("QPushButton{\n"
"    border: 2px solid;\n"
"    border-radius: 5px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(112, 112, 112)\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid;\n"
"    color: rgb(34, 34, 34);\n"
"    background-color:rgb(85, 85, 255)\n"
"}\n"
"")
        self.btn_criar_2.setObjectName("btn_criar_2")
        self.img_do_avatar = QtWidgets.QLabel(self.frame_7)
        self.img_do_avatar.setGeometry(QtCore.QRect(85, 15, 128, 128))
        self.img_do_avatar.setStyleSheet("")
        self.img_do_avatar.setText("")
        self.img_do_avatar.setObjectName("img_do_avatar")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(90, -4, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_25.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.gera_senha = QtWidgets.QFrame(self.conteudoo)
        self.gera_senha.setGeometry(QtCore.QRect(0, 0, 771, 465))
        self.gera_senha.setMinimumSize(QtCore.QSize(771, 465))
        self.gera_senha.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gera_senha.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gera_senha.setObjectName("gera_senha")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gera_senha)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.titulo = QtWidgets.QFrame(self.gera_senha)
        self.titulo.setMaximumSize(QtCore.QSize(16777215, 100))
        self.titulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo.setObjectName("titulo")
        self.label_13 = QtWidgets.QLabel(self.titulo)
        self.label_13.setGeometry(QtCore.QRect(181, 30, 345, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLineWidth(1)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.img_gera_senha = QtWidgets.QLabel(self.titulo)
        self.img_gera_senha.setGeometry(QtCore.QRect(524, 14, 72, 72))
        self.img_gera_senha.setStyleSheet("background-position:center;\n"
"background-size: 72px 72px;")
        self.img_gera_senha.setText("")
        self.img_gera_senha.setObjectName("img_gera_senha")
        self.verticalLayout_6.addWidget(self.titulo)
        self.conteudo = QtWidgets.QFrame(self.gera_senha)
        self.conteudo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.conteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteudo.setObjectName("conteudo")
        self.input_senha = QtWidgets.QLineEdit(self.conteudo)
        self.input_senha.setGeometry(QtCore.QRect(140, 82, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input_senha.setFont(font)
        self.input_senha.setStyleSheet("QLineEdit{\n"
"    color: rgb(135, 135, 135);\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-radius:10px;\n"
"    border: 2px solid rgb(20, 62, 30);\n"
"    padding: 10px 25px\n"
"}\n"
"\n"
"")
        self.input_senha.setMaxLength(15)
        self.input_senha.setReadOnly(True)
        self.input_senha.setPlaceholderText("")
        self.input_senha.setObjectName("input_senha")
        self.btn_gerar = QtWidgets.QPushButton(self.conteudo)
        self.btn_gerar.setGeometry(QtCore.QRect(240, 180, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gerar.setStyleSheet("QPushButton{\n"
"    border: 2px solid;\n"
"    border-radius: 10px;\n"
"    color:white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(31, 93, 45)\n"
"}\n"
"QPushButton:pressed{\n"
"    border: 2px solid;\n"
"    color: white;\n"
"    background-color:rgb(31, 93, 45)\n"
"}\n"
"")
        self.btn_gerar.setObjectName("btn_gerar")
        self.btn_copiar = QtWidgets.QPushButton(self.conteudo)
        self.btn_copiar.setGeometry(QtCore.QRect(544, 88, 48, 48))
        self.btn_copiar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_copiar.setStyleSheet("border-radius:1px;\n"
"background-color: rgb(30, 30, 30);")
        self.btn_copiar.setText("")
        self.btn_copiar.setIconSize(QtCore.QSize(48, 48))
        self.btn_copiar.setObjectName("btn_copiar")
        self.label_senha_gerada = QtWidgets.QLabel(self.conteudo)
        self.label_senha_gerada.setGeometry(QtCore.QRect(146, 145, 111, 32))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_senha_gerada.setFont(font)
        self.label_senha_gerada.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_senha_gerada.setText("")
        self.label_senha_gerada.setObjectName("label_senha_gerada")
        self.img_senha_gerada = QtWidgets.QLabel(self.conteudo)
        self.img_senha_gerada.setGeometry(QtCore.QRect(260, 145, 32, 32))
        self.img_senha_gerada.setStyleSheet("background-position:center;\n"
"background-size: 32px 32px;")
        self.img_senha_gerada.setText("")
        self.img_senha_gerada.setObjectName("img_senha_gerada")
        self.label_copiado = QtWidgets.QLabel(self.conteudo)
        self.label_copiado.setGeometry(QtCore.QRect(610, 97, 78, 32))
        self.label_copiado.setMinimumSize(QtCore.QSize(16, 0))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Demi")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_copiado.setFont(font)
        self.label_copiado.setStyleSheet("background-color: rgb(143, 143, 143);\n"
"border-radius:5px;\n"
"color: rgb(124, 255, 101);")
        self.label_copiado.setText("")
        self.label_copiado.setAlignment(QtCore.Qt.AlignCenter)
        self.label_copiado.setObjectName("label_copiado")
        self.label_14 = QtWidgets.QLabel(self.conteudo)
        self.label_14.setGeometry(QtCore.QRect(88, 320, 91, 16))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.img_seguranca = QtWidgets.QLabel(self.conteudo)
        self.img_seguranca.setGeometry(QtCore.QRect(10, 310, 32, 32))
        self.img_seguranca.setText("")
        self.img_seguranca.setObjectName("img_seguranca")
        self.label_16 = QtWidgets.QLabel(self.conteudo)
        self.label_16.setGeometry(QtCore.QRect(49, 320, 34, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(0, 127, 0);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.conteudo)
        self.info = QtWidgets.QWidget(self.conteudoo)
        self.info.setGeometry(QtCore.QRect(0, 0, 771, 465))
        self.info.setObjectName("info")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.info)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(self.info)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setObjectName("widget")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(50, 5, 691, 91))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(48)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(40, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(211, 211, 211);")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_9.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.info)
        self.widget_2.setObjectName("widget_2")
        self.label_17 = QtWidgets.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(320, 40, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(117, 117, 117);")
        self.label_17.setObjectName("label_17")
        self.info_btn_insta = QtWidgets.QPushButton(self.widget_2)
        self.info_btn_insta.setGeometry(QtCore.QRect(100, 140, 140, 140))
        self.info_btn_insta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info_btn_insta.setStyleSheet("QPushButton{\n"
"    border-radius:70px;\n"
"    background-position:center;\n"
"    background-repeat: no-repeat\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(85, 0, 255)\n"
"}\n"
"\n"
"")
        self.info_btn_insta.setText("")
        self.info_btn_insta.setIconSize(QtCore.QSize(128, 128))
        self.info_btn_insta.setObjectName("info_btn_insta")
        self.info_btn_git = QtWidgets.QPushButton(self.widget_2)
        self.info_btn_git.setGeometry(QtCore.QRect(400, 140, 140, 140))
        self.info_btn_git.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info_btn_git.setStyleSheet("QPushButton{\n"
"    border-radius:70px;\n"
"    background-position:center;\n"
"    background-repeat: no-repeat\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(85, 0, 255)\n"
"}\n"
"\n"
"")
        self.info_btn_git.setText("")
        self.info_btn_git.setIconSize(QtCore.QSize(128, 128))
        self.info_btn_git.setShortcut("")
        self.info_btn_git.setObjectName("info_btn_git")
        self.info_btn_linkedin = QtWidgets.QPushButton(self.widget_2)
        self.info_btn_linkedin.setGeometry(QtCore.QRect(250, 140, 140, 140))
        self.info_btn_linkedin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info_btn_linkedin.setStyleSheet("QPushButton{\n"
"    border-radius:70px;\n"
"    background-position:center;\n"
"    background-repeat: no-repeat\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(85, 0, 255)\n"
"}\n"
"\n"
"")
        self.info_btn_linkedin.setText("")
        self.info_btn_linkedin.setIconSize(QtCore.QSize(128, 128))
        self.info_btn_linkedin.setObjectName("info_btn_linkedin")
        self.info_btn_twitter = QtWidgets.QPushButton(self.widget_2)
        self.info_btn_twitter.setGeometry(QtCore.QRect(550, 138, 140, 140))
        self.info_btn_twitter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info_btn_twitter.setStyleSheet("QPushButton{\n"
"    border-radius:70px;\n"
"    background-position:center;\n"
"    background-repeat: no-repeat\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(85, 0, 255)\n"
"}\n"
"\n"
"")
        self.info_btn_twitter.setText("")
        self.info_btn_twitter.setIconSize(QtCore.QSize(128, 128))
        self.info_btn_twitter.setObjectName("info_btn_twitter")
        self.label_18 = QtWidgets.QLabel(self.widget_2)
        self.label_18.setGeometry(QtCore.QRect(1, 342, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_9.addWidget(self.widget_2)
        self.login.raise_()
        self.gera_senha.raise_()
        self.cadastrar.raise_()
        self.info.raise_()
        self.horizontalLayout.addWidget(self.conteudoo)
        self.verticalLayout.addWidget(self.main)
        self.creditos = QtWidgets.QFrame(self.centralwidget)
        self.creditos.setMinimumSize(QtCore.QSize(0, 20))
        self.creditos.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.creditos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.creditos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.creditos.setObjectName("creditos")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.creditos)
        self.horizontalLayout_18.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtWidgets.QLabel(self.creditos)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(115, 115, 115);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        self.verticalLayout.addWidget(self.creditos)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        '''ATUALIZAÇÕES'''
        self.label_copiado.hide()
        self.info.hide()
        self.label_12.hide()
        self.botao_aba_cadastrar.clicked.connect(self.abri_janela_cadastro)
        self.botao_aba_login.clicked.connect(self.abri_janela_login)
        self.botao_aba_senha.clicked.connect(self.abri_janela_gera_senha)
        self.botao_aba_info.clicked.connect(self.abri_janela_info)
        self.pushButton.setIcon(QIcon('img\\menu.png'))
        self.pushButton.clicked.connect(self.animation)
        self.botao_aba_cadastrar.setEnabled(False)
        self.botao_aba_login.setEnabled(False)
        self.botao_aba_senha.setEnabled(False)
        self.botao_aba_info.setEnabled(False)

    def checkNet(self):
        try:
            requests.get('https://www.google.com/')
        except requests.exceptions.ConnectionError:
            return False
        else:
            return True

    def animation(self):
        if self.menu_conteudo.minimumWidth() == 50:
            self.animação = QPropertyAnimation(self.menu_conteudo, b'minimumWidth')
            self.animação.startTimer(400)
            self.animação.setStartValue(50)
            self.animação.setEndValue(135)
            self.animação.start()

            self.botao_menu = QPropertyAnimation(self.pushButton, b'minimumWidth')
            self.botao_menu.startTimer(400)
            self.botao_menu.setStartValue(50)
            self.botao_menu.setEndValue(135)
            self.botao_menu.start()

            self.botao_aba_cadastrar.setEnabled(True)
            self.botao_aba_login.setEnabled(True)
            self.botao_aba_senha.setEnabled(True)
            if self.checkNet():
                self.botao_aba_info.setEnabled(True)
                self.label_12.show()

            self.botao_aba_cadastrar.setIcon(QIcon('img\\criar_menu.png'))
            self.botao_aba_login.setIcon(QIcon('img\\entrar.png'))
            self.botao_aba_senha.setIcon(QIcon('img\\img_senha.png'))
            if self.checkNet():
                self.botao_aba_info.setIcon(QIcon('img\\info.png'))

        else:
            self.animação = QPropertyAnimation(self.menu_conteudo, b'minimumWidth')
            self.animação.startTimer(400)
            self.animação.setStartValue(135)
            self.animação.setEndValue(50)
            self.animação.start()

            self.botao_menu = QPropertyAnimation(self.pushButton, b'minimumWidth')
            self.botao_menu.startTimer(400)
            self.botao_menu.setStartValue(135)
            self.botao_menu.setEndValue(50)
            self.botao_menu.start()

            self.botao_aba_cadastrar.setEnabled(False)
            self.botao_aba_login.setEnabled(False)
            self.botao_aba_senha.setEnabled(False)
            if self.checkNet():
                self.botao_aba_info.setEnabled(False)


            self.botao_aba_cadastrar.setIcon(QIcon(''))
            self.botao_aba_login.setIcon(QIcon(''))
            self.botao_aba_senha.setIcon(QIcon(''))
            if self.checkNet():
                self.botao_aba_info.setIcon(QIcon(''))

    def abri_janela_cadastro(self):
        self.cadastrar.show()

        self.login.close()
        self.gera_senha.close()
        self.info.close()

    def abri_janela_login(self):
        self.login.show()

        self.cadastrar.close()
        self.gera_senha.close()
        self.info.close()

    def abri_janela_gera_senha(self):
        self.gera_senha.show()

        self.login.close()
        self.cadastrar.close()
        self.info.close()

    def abri_janela_info(self):
        self.info.show()

        self.login.close()
        self.cadastrar.close()
        self.gera_senha.close()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Save"))
        self.label_5.setText(_translate("MainWindow", "CRIAR    "))
        self.label_15.setText(_translate("MainWindow", "ENTRAR"))
        self.label_6.setText(_translate("MainWindow", "CRIPTOGRAFIA  "))
        self.label_12.setText(_translate("MainWindow", "INFO DEV  "))
        self.label_3.setText(_translate("MainWindow", "CONTAS"))
        self.label_4.setText(_translate("MainWindow", "                  ENTRAR"))
        self.label_9.setText(_translate("MainWindow", "                                       NOME"))
        self.label_11.setText(_translate("MainWindow", "APAGAR"))
        self.label_8.setText(_translate("MainWindow", "LIMITE: 14 CONTAS"))
        self.label_2.setText(_translate("MainWindow", "CADASTRAR"))
        self.input_nome_2.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.input_sobrenome_2.setPlaceholderText(_translate("MainWindow", "SOBRENOME"))
        self.btn_criar_2.setText(_translate("MainWindow", "CRIAR CONTA"))
        self.label_7.setText(_translate("MainWindow", "Selecione um avatar"))
        self.label_13.setText(_translate("MainWindow", "SENHA CRIPTOGRAFADA"))
        self.btn_gerar.setText(_translate("MainWindow", "GERAR"))
        self.label_14.setText(_translate("MainWindow", "DE SEGURANÇA"))
        self.label_16.setText(_translate("MainWindow", "100% "))
        self.label_10.setText(_translate("MainWindow", "Ryan Barbosa Silva"))
        self.label_19.setText(_translate("MainWindow", "DEV"))
        self.label_17.setText(_translate("MainWindow", "Redes sociais"))
        self.label_18.setText(_translate("MainWindow", "Mais projeto no github."))
        self.label.setText(_translate("MainWindow", "Criado por: @ry4nzk"))
